/*
 * Copyright (c) 2026 WindRPC
 *
 * SPDX-License-Identifier: MIT
 */

/**
 * COBS (Consistent Overhead Byte Stuffing) for WindRPC Client
 * Auto-generated by WindRPC tool.
 */

export function cobsEncode(inputData) {
    const input = (inputData && inputData.length !== undefined) ? Uint8Array.from(inputData) : new Uint8Array(inputData || 0);
    const output = [];
    let codeIndex = 0;
    let code = 1;

    output.push(0);

    for (let i = 0; i < input.length; i++) {
        if (input[i] !== 0) {
            output.push(input[i]);
            code++;
        }

        if (input[i] === 0 || code === 0xFF) {
            output[codeIndex] = code;
            codeIndex = output.length;
            output.push(0);
            code = 1;
        }
    }

    output[codeIndex] = code;
    return new Uint8Array(output);
}

export function cobsDecode(inputData) {
    const input = (inputData && inputData.length !== undefined) ? Uint8Array.from(inputData) : new Uint8Array(inputData || 0);
    const output = [];
    let i = 0;

    while (i < input.length) {
        let code = input[i];
        if (code === 0) break;

        i++;
        for (let j = 1; j < code; j++) {
            if (i < input.length) {
                output.push(input[i++]);
            }
        }

        if (code < 0xFF && i < input.length && input[i] !== 0) {
            output.push(0);
        }
    }

    return new Uint8Array(output);
}

