// Auto-generated by WindRPC tool powered by protobufjs. Do not modify manually.
import protobuf from 'protobufjs';
import { cobsEncode, cobsDecode } from './cobs.js';

export const RPC_ID = {
// --WINDRPC_RPC_ID_CONSTANTS
};

// Protobuf Descriptor Schema
export const PROTO_SCHEMA = // --WINDRPC_PROTO_SCHEMA;

const root = protobuf.Root.fromJSON(PROTO_SCHEMA);

// --WINDRPC_MESSAGE_HELPERS

export class WindRpcClient {
    constructor() {
        this.seqId = 0;
        this._pendingRequests = new Map();
        this._rxBuffer = [];
// --WINDRPC_SUB_CLIENT_INIT
    }

    getNextSeqId() {
        this.seqId = (this.seqId + 1) & 0xFFFF;
        return this.seqId;
    }

    /**
     * Builds a raw WindRPC COBS frame.
     * Frame format: COBS(RPC_ID[2] + SEQ_ID[2] + PAYLOAD_LEN[1] + PAYLOAD) + 0x00
     */
    buildFrame(rpcId, payloadBytes = new Uint8Array(0)) {
        const seqId = this.getNextSeqId();
        const payloadLen = payloadBytes.length;
        const header = new Uint8Array(5);
        header[0] = (rpcId >> 8) & 0xFF;
        header[1] = rpcId & 0xFF;
        header[2] = (seqId >> 8) & 0xFF;
        header[3] = seqId & 0xFF;
        header[4] = payloadLen & 0xFF;

        const rawPacket = new Uint8Array(5 + payloadLen);
        rawPacket.set(header, 0);
        if (payloadLen > 0) rawPacket.set(payloadBytes, 5);

        const encoded = cobsEncode(rawPacket);
        const frame = new Uint8Array(encoded.length + 1);
        frame.set(encoded, 0);
        frame[encoded.length] = 0x00;
        return frame;
    }

    /**
     * Feed received serial bytes into the RX state machine.
     * Splits on 0x00 delimiter, COBS-decodes, dispatches responses/notifications.
     * @param {Uint8Array|number[]} data - raw bytes from serial port
     * @param {function} onNotification - called with {rpcId, seqId, payload}
     */
    receiveBytes(data, onNotification) {
        for (const byte of data) {
            if (byte === 0x00) {
                if (this._rxBuffer.length > 0) {
                    const decoded = cobsDecode(new Uint8Array(this._rxBuffer));
                    this._rxBuffer = [];
                    this._dispatchFrame(decoded, onNotification);
                }
            } else {
                this._rxBuffer.push(byte);
            }
        }
    }

    _dispatchFrame(decoded, onNotification) {
        if (decoded.length < 5) return;
        const rpcId = (decoded[0] << 8) | decoded[1];
        const seqId = (decoded[2] << 8) | decoded[3];
        const payLen = decoded[4];
        const payload = decoded.slice(5, 5 + payLen);

        const pending = this._pendingRequests.get(seqId);
        if (pending) {
            this._pendingRequests.delete(seqId);
            pending.resolve({ rpcId, seqId, payload });
            return;
        }

        if (onNotification && typeof onNotification === 'function') {
            onNotification({ rpcId, seqId, payload });
        }
    }

    /**
     * Send a frame and return a Promise that resolves with the response.
     * Requires the caller to also call receiveBytes() when data arrives.
     */
    sendRequest(rpcId, payloadBytes, sendFn, timeoutMs = 2000) {
        const seqId = this.seqId + 1;  // peek at next seqId
        const frame = this.buildFrame(rpcId, payloadBytes);
        return new Promise((resolve, reject) => {
            const timer = setTimeout(() => {
                this._pendingRequests.delete(seqId);
                reject(new Error(`RPC timeout: rpcId=0x${rpcId.toString(16)}`));
            }, timeoutMs);
            this._pendingRequests.set(seqId & 0xFFFF, {
                resolve: (v) => { clearTimeout(timer); resolve(v); },
                reject:  (e) => { clearTimeout(timer); reject(e); },
            });
            sendFn(frame);
        });
    }
}

// --WINDRPC_SERVICE_CLIENT_CLASSES

export const windRpcClient = new WindRpcClient();
