/*
 * Copyright (c) 2026 WindRPC
 *
 * SPDX-License-Identifier: MIT
 */

// Auto-generated by WindRPC tool powered by protobufjs. Do not modify manually.
import protobuf from 'protobufjs';
import { cobsEncode, cobsDecode } from './cobs.js';
export { cobsEncode, cobsDecode } from './cobs.js';

export const RPC_ID = {
// --WINDRPC_RPC_ID_CONSTANTS
};

// Protobuf Descriptor Schema
export const PROTO_SCHEMA = // --WINDRPC_PROTO_SCHEMA;

const root = protobuf.Root.fromJSON(PROTO_SCHEMA);

// --WINDRPC_MESSAGE_HELPERS

export class WindRpcClient {
    constructor() {
        this.seqId = 0;
        this._pendingRequests = new Map();
        this._rxAccumulator = [];
// --WINDRPC_SUB_CLIENT_INIT
    }

    getNextSeqId() {
        this.seqId = (this.seqId + 1) & 0xFFFF;
        return this.seqId;
    }

    resetAccumulator() {
        this._rxAccumulator = [];
        for (const [seqId, pending] of this._pendingRequests.entries()) {
            pending.reject(new Error('Transport reset'));
        }
        this._pendingRequests.clear();
    }

    /**
     * Builds a raw WindRPC binary frame without COBS encoding by default.
     * Raw Frame format: RPC_ID[2] + SEQ_ID[2] + PAYLOAD_LEN[1] + PAYLOAD
     * @param {number} rpcId - 16-bit combined RPC ID
     * @param {Uint8Array} payloadBytes - encoded Protobuf payload
     * @returns {Uint8Array} raw binary packet
     */
    buildFrame(rpcId, payloadBytes = new Uint8Array(0)) {
        return this.buildRawFrame(rpcId, payloadBytes);
    }

    buildRawFrame(rpcId, payloadBytes = new Uint8Array(0)) {
        const seqId = this.getNextSeqId();
        const payloadLen = payloadBytes.length;
        const header = new Uint8Array(5);
        header[0] = (rpcId >> 8) & 0xFF;
        header[1] = rpcId & 0xFF;
        header[2] = (seqId >> 8) & 0xFF;
        header[3] = seqId & 0xFF;
        header[4] = payloadLen & 0xFF;

        const rawPacket = new Uint8Array(5 + payloadLen);
        rawPacket.set(header, 0);
        if (payloadLen > 0) rawPacket.set(payloadBytes, 5);
        return rawPacket;
    }

    /**
     * Builds a COBS-framed WindRPC binary packet ready to send over serial byte streams (USB-CDC, UART).
     * Output: COBS_ENCODED_BYTES + 0x00
     */
    buildCobsFrame(rpcId, payloadBytes = new Uint8Array(0)) {
        const rawPacket = this.buildRawFrame(rpcId, payloadBytes);
        const encoded = cobsEncode(rawPacket);
        const framed = new Uint8Array(encoded.length + 1);
        framed.set(encoded, 0);
        framed[encoded.length] = 0;
        return framed;
    }

    /**
     * Feed a received raw UDP datagram frame directly into the RX state machine without COBS decoding.
     */
    receiveRawDatagram(bytes, onNotification) {
        if (!bytes) return;
        const decoded = (bytes instanceof Uint8Array) ? bytes : new Uint8Array(bytes);
        if (decoded && decoded.length >= 5) {
            this._dispatchFrame(decoded, onNotification);
        }
    }

    receiveFrame(frame, onNotification) {
        this.receiveRawDatagram(frame, onNotification);
    }

    /**
     * Accumulates incoming serial byte chunks until a 0x00 delimiter,
     * then decodes COBS packet and dispatches to pending RPC requests.
     */
    receiveBytes(bytes, onNotification) {
        if (!bytes) return;
        const incoming = (bytes instanceof Uint8Array) ? bytes : new Uint8Array(bytes);
        for (let i = 0; i < incoming.length; i++) {
            const b = incoming[i];
            if (b === 0x00) {
                if (this._rxAccumulator.length > 0) {
                    const cobsPacket = new Uint8Array(this._rxAccumulator);
                    this._rxAccumulator = [];
                    try {
                        const decoded = cobsDecode(cobsPacket);
                        if (decoded && decoded.length >= 5) {
                            this._dispatchFrame(decoded, onNotification);
                        }
                    } catch (err) {
                        console.warn('[WindRPC] COBS decode error:', err);
                    }
                }
            } else {
                this._rxAccumulator.push(b);
                if (this._rxAccumulator.length > 4096) {
                    this._rxAccumulator = [];
                }
            }
        }
    }

    _dispatchFrame(decoded, onNotification) {
        if (decoded.length < 5) return;
        const rpcId = (decoded[0] << 8) | decoded[1];
        const seqId = (decoded[2] << 8) | decoded[3];
        const payLen = decoded[4];
        const payload = decoded.slice(5, 5 + payLen);

        const pending = this._pendingRequests.get(seqId);
        if (pending) {
            this._pendingRequests.delete(seqId);
            if (rpcId === 0x0000) {
                try {
                    const status = (typeof decodeStatus === 'function') ? decodeStatus(payload) : { code: -1, message: 'Server error' };
                    pending.reject(new Error(`[WindRPC Status Error ${status.code}] ${status.message || 'Server error'}`));
                } catch (err) {
                    pending.reject(new Error(`[WindRPC Status Error] Unknown server error (rpcId=0x0000)`));
                }
            } else {
                pending.resolve({ rpcId, seqId, payload });
            }
            return;
        }

        if (onNotification && typeof onNotification === 'function') {
            onNotification({ rpcId, seqId, payload });
        }
    }

    /**
     * Send a frame and return a Promise that resolves with the response.
     * Requires the caller to also call receiveBytes() when data arrives.
     */
    sendRequest(rpcId, payloadBytes, sendFn, timeoutMs = 2000) {
        const frame = this.buildFrame(rpcId, payloadBytes);
        const reqSeqId = this.seqId;
        return new Promise((resolve, reject) => {
            const timer = setTimeout(() => {
                this._pendingRequests.delete(reqSeqId);
                reject(new Error(`RPC timeout: rpcId=0x${rpcId.toString(16)}`));
            }, timeoutMs);
            this._pendingRequests.set(reqSeqId, {
                resolve: (v) => { clearTimeout(timer); resolve(v); },
                reject:  (e) => { clearTimeout(timer); reject(e); },
            });
            sendFn(frame);
        });
    }
}

// --WINDRPC_SERVICE_CLIENT_CLASSES

export const windRpcClient = new WindRpcClient();

