// Auto-generated by WindRPC tool powered by protobufjs. Do not modify manually.
import protobuf from 'protobufjs';
import { cobsEncode, cobsDecode } from './cobs.js';

export const RPC_ID = {
// --WINDRPC_RPC_ID_CONSTANTS
};

// Protobuf Descriptor Schema
export const PROTO_SCHEMA = // --WINDRPC_PROTO_SCHEMA;

const root = protobuf.Root.fromJSON(PROTO_SCHEMA);

// --WINDRPC_MESSAGE_HELPERS

export class WindRpcClient {
    constructor() {
        this.seqId = 0;
        this._pendingRequests = new Map();
// --WINDRPC_SUB_CLIENT_INIT
    }

    getNextSeqId() {
        this.seqId = (this.seqId + 1) & 0xFFFF;
        return this.seqId;
    }

    /**
     * Builds a COBS-framed WindRPC binary packet ready to send over serial.
     * Raw Frame format: RPC_ID[2] + SEQ_ID[2] + PAYLOAD_LEN[1] + PAYLOAD
     * Output: COBS_ENCODED_BYTES + 0x00
     * @param {number} rpcId - 16-bit combined RPC ID
     * @param {Uint8Array} payloadBytes - encoded Protobuf payload
     * @returns {Uint8Array} COBS-framed binary packet
     */
    buildFrame(rpcId, payloadBytes = new Uint8Array(0)) {
        const seqId = this.getNextSeqId();
        const payloadLen = payloadBytes.length;
        const header = new Uint8Array(5);
        header[0] = (rpcId >> 8) & 0xFF;
        header[1] = rpcId & 0xFF;
        header[2] = (seqId >> 8) & 0xFF;
        header[3] = seqId & 0xFF;
        header[4] = payloadLen & 0xFF;

        const rawPacket = new Uint8Array(5 + payloadLen);
        rawPacket.set(header, 0);
        if (payloadLen > 0) rawPacket.set(payloadBytes, 5);

        const encoded = cobsEncode(rawPacket);
        const framed = new Uint8Array(encoded.length + 1);
        framed.set(encoded, 0);
        framed[encoded.length] = 0;
        return framed;
    }

    /**
     * Alias for receiveFrame for streaming/serial byte reception.
     */
    receiveBytes(bytes, onNotification) {
        this.receiveFrame(bytes, onNotification);
    }

    /**
     * Feed a received raw WindRPC frame into the RX state machine.
     * Decodes COBS if necessary before dispatching.
     * @param {Uint8Array} frame - raw binary frame packet
     * @param {function} onNotification - called with {rpcId, seqId, payload}
     */
    receiveFrame(frame, onNotification) {
        if (!frame) return;
        const bytes = Uint8Array.from(frame);
        if (bytes.length < 5) return;
        let unencoded = bytes;
        try {
            const cleanBytes = (bytes[bytes.length - 1] === 0) ? bytes.subarray(0, bytes.length - 1) : bytes;
            const decoded = cobsDecode(cleanBytes);
            if (decoded && decoded.length >= 5) {
                unencoded = decoded;
            }
        } catch (e) {
            // fallback to raw frame if already decoded
        }
        this._dispatchFrame(unencoded, onNotification);
    }

    _dispatchFrame(decoded, onNotification) {
        if (decoded.length < 5) return;
        const rpcId = (decoded[0] << 8) | decoded[1];
        const seqId = (decoded[2] << 8) | decoded[3];
        const payLen = decoded[4];
        const payload = decoded.slice(5, 5 + payLen);

        const pending = this._pendingRequests.get(seqId);
        if (pending) {
            this._pendingRequests.delete(seqId);
            if (rpcId === 0x0000) {
                try {
                    const status = (typeof decodeStatus === 'function') ? decodeStatus(payload) : { code: -1, message: 'Server error' };
                    pending.reject(new Error(`[WindRPC Status Error ${status.code}] ${status.message || 'Server error'}`));
                } catch (err) {
                    pending.reject(new Error(`[WindRPC Status Error] Unknown server error (rpcId=0x0000)`));
                }
            } else {
                pending.resolve({ rpcId, seqId, payload });
            }
            return;
        }

        if (onNotification && typeof onNotification === 'function') {
            onNotification({ rpcId, seqId, payload });
        }
    }

    /**
     * Send a frame and return a Promise that resolves with the response.
     * Requires the caller to also call receiveBytes() when data arrives.
     */
    sendRequest(rpcId, payloadBytes, sendFn, timeoutMs = 2000) {
        const seqId = this.seqId + 1;  // peek at next seqId
        const frame = this.buildFrame(rpcId, payloadBytes);
        return new Promise((resolve, reject) => {
            const timer = setTimeout(() => {
                this._pendingRequests.delete(seqId);
                reject(new Error(`RPC timeout: rpcId=0x${rpcId.toString(16)}`));
            }, timeoutMs);
            this._pendingRequests.set(seqId & 0xFFFF, {
                resolve: (v) => { clearTimeout(timer); resolve(v); },
                reject:  (e) => { clearTimeout(timer); reject(e); },
            });
            sendFn(frame);
        });
    }
}

// --WINDRPC_SERVICE_CLIENT_CLASSES

export const windRpcClient = new WindRpcClient();
