# windrpc/client/python.py
import json
import os


def to_snake(name):
    if not name:
        return ""
    import re
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def to_pascal(name):
    if not name:
        return ""
    parts = name.split('_')
    return "".join(p.capitalize() for p in parts if p)


def generate_python_client(spec_data, package_name):
    """
    Generates a single-file WindRpcClient.py SDK in Python.
    Includes zero-dependency 6-byte binary header framing, COBS encoding/decoding,
    transport-agnostic byte & datagram RX dispatchers, and async/sync request methods.
    """
    services = spec_data.get('services', [])
    rpc_map = {}

    # Build RPC ID Constants & Mapping
    for svc in services:
        svc_id = svc.get('id', 0)
        svc_name = svc.get('name', 'service')
        for rpc in svc.get('rpcs', []):
            rpc_id_num = rpc.get('id', 0)
            rpc_name = rpc.get('name', 'rpc')
            rpc_type = rpc.get('type', 'REQUEST_RESPONSE')

            # Calculate 16-bit Combined RPC ID
            if rpc_type == 'NOTIFICATION':
                combined_id = (svc_id << 8) | (rpc_id_num | 0x80)
            else:
                combined_id = (svc_id << 8) | rpc_id_num

            const_name = f"RPC_{svc_name.upper()}_{rpc_name.upper()}"
            rpc_map[const_name] = {
                "id": combined_id,
                "hex": f"0x{combined_id:04X}",
                "service": svc_name,
                "rpc": rpc_name,
                "type": rpc_type,
                "command": rpc.get('command', 'Empty'),
                "result": rpc.get('result', 'Empty')
            }

    code = f'''# Auto-generated by WindRPC Generator Engine for Python
# Package: {package_name}
# DO NOT EDIT DIRECTLY. Always modify user_spec.yml and re-run windrpc_gen.py.

import struct
import time
import asyncio
from typing import Callable, Optional, Dict, Any, Tuple


# =========================================================================
# COBS (Consistent Overhead Byte Stuffing) Utility Module
# =========================================================================
def cobs_encode(data: bytes) -> bytes:
    """Encodes bytes into COBS framed bytes with trailing 0x00 delimiter."""
    if not data:
        return b'\\x01\\x00'

    dest = bytearray()
    code_idx = len(dest)
    dest.append(0)
    code = 1

    for byte in data:
        if byte != 0:
            dest.append(byte)
            code += 1
            if code == 0xFF:
                dest[code_idx] = code
                code_idx = len(dest)
                dest.append(0)
                code = 1
        else:
            dest[code_idx] = code
            code_idx = len(dest)
            dest.append(0)
            code = 1

    dest[code_idx] = code
    dest.append(0)  # Add 0x00 delimiter
    return bytes(dest)


def cobs_decode(data: bytes) -> bytes:
    """Decodes COBS framed bytes (with or without trailing 0x00 delimiter)."""
    if not data:
        return b''
    if data[-1] == 0:
        data = data[:-1]
    if not data:
        return b''

    dest = bytearray()
    idx = 0
    length = len(data)

    while idx < length:
        code = data[idx]
        if code == 0:
            raise ValueError("Invalid zero byte found inside COBS payload body")
        idx += 1
        for i in range(1, code):
            if idx >= length:
                break
            dest.append(data[idx])
            idx += 1
        if code < 0xFF and idx < length:
            dest.append(0)

    return bytes(dest)


# =========================================================================
# Generated RPC Constants
# =========================================================================
'''
    for const_name, info in rpc_map.items():
        code += f"{const_name} = {info['hex']}  # Service '{info['service']}', RPC '{info['rpc']}' ({info['type']})\n"

    code += f'''

# =========================================================================
# WindRpcClient Core SDK Class
# =========================================================================
class WindRpcFrame:
    def __init__(self, rpc_id: int, seq_id: int, payload: bytes):
        self.rpc_id = rpc_id
        self.seq_id = seq_id
        self.payload = payload

    def __repr__(self):
        return f"<WindRpcFrame RPC_ID=0x{{self.rpc_id:04X}} SEQ={{self.seq_id}} LEN={{len(self.payload)}}>"


class WindRpcClient:
    """
    Zero-heap, static binary header WindRPC Client SDK for Python.
    Supports UART/USB-CDC COBS stream framing and raw packet datagrams (UDP/BLE).
    """

    def __init__(self):
        self._next_seq_id = 1
        self._rx_buffer = bytearray()
        self._pending_requests: Dict[int, Tuple[asyncio.Future, float]] = {{}}

    def _get_next_seq_id(self) -> int:
        seq = self._next_seq_id
        self._next_seq_id = (self._next_seq_id % 0xFFFF) + 1
        return seq

    def pack_frame(self, rpc_id: int, seq_id: int, payload: bytes) -> bytes:
        """Packs 6-byte raw binary header + payload."""
        header = struct.pack('<HHH', rpc_id, seq_id, len(payload))
        return header + payload

    def unpack_frame(self, data: bytes) -> WindRpcFrame:
        """Unpacks 6-byte raw binary header + payload from a complete packet."""
        if len(data) < 6:
            raise ValueError(f"Packet length {{len(data)}} is less than 6-byte binary header size")
        rpc_id, seq_id, payload_len = struct.unpack('<HHH', data[:6])
        payload = data[6:6 + payload_len]
        return WindRpcFrame(rpc_id, seq_id, payload)

    def receive_raw_datagram(self, data: bytes, on_notification: Optional[Callable[[WindRpcFrame], None]] = None) -> Optional[WindRpcFrame]:
        """
        Processes a raw un-framed binary datagram packet (e.g. UDP, BLE).
        Dispatches notifications to on_notification callback and completes matching pending request futures.
        """
        if len(data) < 6:
            return None

        frame = self.unpack_frame(data)

        # 1. System Error Response (RPC_ID 0x0000)
        if frame.rpc_id == 0x0000:
            if frame.seq_id in self._pending_requests:
                fut, _ = self._pending_requests.pop(frame.seq_id)
                if not fut.done():
                    fut.set_exception(RuntimeError(f"System Error returned from RPC Server for SEQ {{frame.seq_id}}"))
            return frame

        # 2. Notification Event (bit 7 set in low byte)
        if (frame.rpc_id & 0x80) != 0:
            if on_notification:
                on_notification(frame)
            return frame

        # 3. Response Frame
        if frame.seq_id in self._pending_requests:
            fut, _ = self._pending_requests.pop(frame.seq_id)
            if not fut.done():
                fut.set_result(frame)

        return frame

    def receive_bytes(self, chunk: bytes, on_notification: Optional[Callable[[WindRpcFrame], None]] = None):
        """
        Processes streaming bytes (e.g. Serial / UART) using COBS delimiter 0x00.
        """
        self._rx_buffer.extend(chunk)

        while True:
            try:
                delimiter_idx = self._rx_buffer.index(0)
            except ValueError:
                break

            cobs_packet = bytes(self._rx_buffer[:delimiter_idx])
            del self._rx_buffer[:delimiter_idx + 1]

            if not cobs_packet:
                continue

            try:
                raw_packet = cobs_decode(cobs_packet)
                self.receive_raw_datagram(raw_packet, on_notification)
            except Exception as e:
                # Ignore corrupt frames in serial stream
                pass

    async def send_request_async(
        self,
        rpc_id: int,
        payload: bytes,
        transport_send_fn: Callable[[bytes], None],
        timeout_ms: int = 3000,
        cobs_encode_frame: bool = False
    ) -> WindRpcFrame:
        """
        Sends an asynchronous RPC request and awaits the matching response frame.
        """
        seq_id = self._get_next_seq_id()
        raw_frame = self.pack_frame(rpc_id, seq_id, payload)
        send_data = cobs_encode(raw_frame) if cobs_encode_frame else raw_frame

        loop = asyncio.get_running_loop()
        fut = loop.create_future()
        self._pending_requests[seq_id] = (fut, time.time())

        # Send via transport
        transport_send_fn(send_data)

        try:
            return await asyncio.wait_for(fut, timeout=timeout_ms / 1000.0)
        except asyncio.TimeoutError:
            self._pending_requests.pop(seq_id, None)
            raise TimeoutError(f"RPC Request 0x{{rpc_id:04X}} timed out after {{timeout_ms}} ms (SEQ: {{seq_id}})")
'''
    return code
