# proto/generator.py
from utils.spec import merge_specs, combine_ids
from utils.converter import to_pascal_case, enum_value_prefix, apply_enum_prefix
from utils.loader import LineNumberLoader
from utils import spec_validator
from . import options_generator
import yaml
import os
import sys

# 경로 설정을 통해 utils 폴더의 모듈을 임포트합니다.
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
sys.path.append(parent_dir)


declared_all_types = dict()


# --- 포맷팅 헬퍼 함수 ---
def get_generated_file_header():
    """자동 생성된 .proto 파일의 표준 헤더를 반환합니다."""
    return "// Copyright (c) 2026 WindRPC\n//\n// SPDX-License-Identifier: MIT\n//\n// This file is automatically generated. Do not modify.\n"

# NOTE: proto syntax
# Although Protobuf Editions (e.g. edition = "2023") is the modern replacement
# for proto2/proto3, the Nanopb library (nanopb/nanopb) used on the C MCU side
# does not currently (as of 2026) support Protobuf Editions.
# The nanopb generator plugin cannot interpret edition-based feature flags,
# so we maintain syntax = "proto3" until nanopb officially supports Editions.


def format_field(field):
    """단일 Protobuf 필드 라인을 포맷합니다."""
    prop = field.get('property', '').strip()
    prefix = f"{prop} " if prop in ["repeated", "optional"] else ""
    field_str = f"  {prefix}{field['type']} {field['name']} = {field['number']};"
    if 'description' in field:
        field_str += f" // {field['description']}"
    return field_str


def generate_reserved_statement(yaml_reserved_list):
    if not yaml_reserved_list:
        return None
    numbers, names = [], []
    for item in yaml_reserved_list:
        if isinstance(item, int):
            numbers.append(str(item))
        elif isinstance(item, str):
            if ' to ' in item:
                numbers.append(item)
            else:
                names.append(f'"{item}"')
    statements = []
    if numbers:
        statements.append(f"  reserved {', '.join(numbers)};")
    if names:
        statements.append(f"  reserved {', '.join(names)};")
    return "\n".join(statements) if statements else None


def format_enum_item(item, prefix):
    """enum 멤버를 proto 스타일로 포맷합니다. prefix 자동 적용 포함."""
    name = apply_enum_prefix(item['name'], prefix)
    return f"  {name} = {item['value']};"


def generate_enums_from_spec(enums_to_process):
    content = []
    for enum_def in enums_to_process:
        content.append(f"enum {to_pascal_case(enum_def['name'])} {{")
        # Proto 스타일 가이드: enum 값 접두어 자동 적용
        # spec의 'prefix' 키 우선, 없으면 enum 타입명에서 자동 계산
        explicit_prefix = enum_def.get('prefix', None)
        prefix = enum_value_prefix(enum_def['name'], explicit_prefix)
        current_value = 0
        for item in enum_def['members']:
            item['value'] = item.get('value', current_value)
            content.append(format_enum_item(item, prefix))
            current_value = item['value'] + 1
        reserved_stmt = generate_reserved_statement(
            enum_def.get('reserved', []))
        if reserved_stmt:
            content.append(reserved_stmt)
        content.append('}\n')
    return "\n".join(content)


def get_all_types(spec_data):
    declared_all_types['types'] = {m.get('name') for m in spec_data.get('types', {}).get('messages', [])} | \
        {e.get('name') for e in spec_data.get('types', {}).get('enums', [])}

    for svc in spec_data.get('services', []):
        declared_all_types[svc.get('name')] = {(m.get('name')) for m in svc.get('messages', [])} | \
            {(e.get('name')) for e in svc.get('enums', [])}

    # print(declared_all_types)


def generate_import_paths(type_names):
    import_paths = []
    scalar_types = {'double', 'float', 'int32', 'int64', 'uint32', 'uint64', 'sint32',
                    'sint64', 'fixed32', 'fixed64', 'sfixed32', 'sfixed64', 'bool', 'string', 'bytes'}
    for type_name in type_names:
        if type_name in scalar_types:
            continue
        parts = type_name.split('.')
        # print(type_name)
        if len(parts) >= 2:
            new_parts = parts[:-1]
            if new_parts[-1] == 'types':
                new_parts[-1] += '/types.proto'
            else:
                new_parts[-1] += '.proto'
            import_path = f'import "{"/".join(new_parts)}";'
            if import_path not in import_paths:
                import_paths.append(import_path)
    # print(import_paths)
    return import_paths


# --- [최종 수정] 타입 이름 해석 함수 ---
def resolve_type_name(type_name, current_service_name, spec_data, package_prefix):
    """
    타입 이름을 올바른 전체 경로로 변환합니다.
    - 'types.Empty' -> 'package.types.Empty'
    - 'Empty' -> 'package.types.Empty' (공용 타입일 경우)
    - 'PixelData' -> 'PixelData' (같은 서비스 내 지역 타입일 경우)
    """
    # if not isinstance(type_name, str):
    #     return to_pascal_case(str(type_name))
    # print(declared_all_types)

    scalar_types = {'double', 'float', 'int32', 'int64', 'uint32', 'uint64', 'sint32',
                    'sint64', 'fixed32', 'fixed64', 'sfixed32', 'sfixed64', 'bool', 'string', 'bytes'}
    if type_name.lower() in scalar_types:
        return type_name.lower()

    # # 1. 모든 알려진 사용자 정의 타입을 {단순이름: 전체경로} 맵으로 사전 계산
    # # common_types = {to_pascal_case(m.get('name')) for m in spec_data.get('types', {}).get('messages', [])} | \
    # #                {to_pascal_case(e.get('name')) for e in spec_data.get('types', {}).get('enums', [])}
    # common_types = {m.get('name') for m in spec_data.get('types', {}).get('messages', [])} | \
    #                {e.get('name') for e in spec_data.get('types', {}).get('enums', [])}

    # another_types = set()
    # local_types = set()
    # # if current_service_name:
    # for svc in spec_data.get('services', []):
    #     if svc.get('name') == current_service_name:
    #         # local_types = {to_pascal_case(m.get('name')) for m in svc.get('messages', [])} | \
    #         #               {to_pascal_case(e.get('name')) for e in svc.get('enums', [])}
    #         # break
    #         local_types = {(m.get('name')) for m in svc.get('messages', [])} | \
    #                         {(e.get('name')) for e in svc.get('enums', [])}
    #     else :
    #         another_types |= {(m.get('name')) for m in svc.get('messages', [])} | \
    #                         {(e.get('name')) for e in svc.get('enums', [])}

    # 2. 입력된 타입 이름의 가장 마지막 부분(실제 타입명)을 추출
    # simple_name = to_pascal_case(type_name.split('.')[-1])
    simple_name = type_name.split('.')[-1]

    # 3. 타입 확인 및 전체 경로 반환
    # 지역 타입이 우선순위가 가장 높음
    # if simple_name in local_types:
    if current_service_name is not None and simple_name in declared_all_types[current_service_name]:
        return simple_name

    # 그 다음 공용 타입
    # if simple_name in common_types:
    if simple_name in declared_all_types["types"]:
        return f"{package_prefix}.windrpc.types.{simple_name}"

    # 마지막 다른 서비스타입
    parts = type_name.split('.')
    sub_package_name = parts[-2] if len(parts) >= 2 else None
    if sub_package_name is not None:
        if simple_name in declared_all_types[sub_package_name]:
            return f"{package_prefix}.windrpc.service.{type_name}"

    # 그 외 (다른 서비스의 타입 등)는 입력된 대로 반환 (마지막 부분은 PascalCase)
    parts = type_name.split('.')
    parts[-1] = simple_name
    return ".".join(parts)


# --- .proto 파일 생성 함수들 ---

def generate_types_proto(spec_data, package_prefix):
    content = [get_generated_file_header(), 'syntax = "proto3";\n',
               f"package {package_prefix}.windrpc.types;\n"]
    resolved_type_names = []
    types_spec = spec_data.get('types', {})
    content.append(generate_enums_from_spec(types_spec.get('enums', [])))
    for msg_def in types_spec.get('messages', []):
        content.append(f"message {to_pascal_case(msg_def['name'])} {{")
        reserved_stmt = generate_reserved_statement(
            msg_def.get('reserved', []))
        if reserved_stmt:
            content.append(reserved_stmt)
        for oneof_def in msg_def.get('oneofs', []):
            content.append(f"  oneof {oneof_def['name']} {{")
            for field in oneof_def.get('fields', []):
                field['type'] = resolve_type_name(
                    field['type'], None, spec_data, package_prefix)
                resolved_type_names.append(field['type'])
                content.append(f"  {format_field(field)}")
            content.append("  }")
        for field in msg_def.get('fields', []):
            field['type'] = resolve_type_name(
                field['type'], None, spec_data, package_prefix)
            resolved_type_names.append(field['type'])
            content.append(format_field(field))
        content.append("}\n")

    import_paths = generate_import_paths(resolved_type_names)
    if len(import_paths) > 0:
        content.insert(3, "\n".join(import_paths))

    return "\n".join(content)


def generate_service_proto(service_spec, spec_data, package_prefix):
    service_name = service_spec['name']
    svc_id = service_spec.get('id', 0)
    content = [get_generated_file_header(), 'syntax = "proto3";\n',
               f"package {package_prefix}.windrpc.service.{service_name};\n"]

    doc_lines = ["/**"]
    doc_lines.append(f" * Service: {service_name} (ID: {svc_id})")
    doc_lines.append(" * RPC Methods:")
    for rpc in service_spec.get('rpcs', []):
        rpc_type = rpc.get('type', '').upper()
        rpc_name = rpc['name']
        rpc_id = rpc['id']
        combined_id = (svc_id << 8) | rpc_id
        desc = rpc.get('description', rpc.get('summary', ''))
        desc_str = f" - {desc}" if desc else ""
        if rpc_type == 'REQUEST_ONLY':
            doc_lines.append(f" *  - {rpc_name} (0x{combined_id:04X}): param={rpc.get('command', 'types.Empty')}, return=void{desc_str}")
        elif rpc_type == 'REQUEST_RESPONSE':
            doc_lines.append(f" *  - {rpc_name} (0x{combined_id:04X}): param={rpc.get('command', 'types.Empty')}, return={rpc.get('result', 'types.Empty')}{desc_str}")
        elif rpc_type == 'NOTIFICATION':
            event_combined_id = (svc_id << 8) | (rpc_id | 0x80)
            doc_lines.append(f" *  - subscribe_{rpc_name} (0x{combined_id:04X}): param=types.Subscribe, return=types.Empty")
            doc_lines.append(f" *  - {rpc_name} Event (0x{event_combined_id:04X}): event={rpc.get('event', 'types.Empty')}{desc_str}")
    doc_lines.append(" */\n")
    content.append("\n".join(doc_lines))

    imports_to_add = set()
    all_type_names = []
    resolved_type_names = []

    for msg_def in service_spec.get('messages', []):
        for field in msg_def.get('fields', []):
            all_type_names.append(field.get('type'))
        for oneof in msg_def.get('oneofs', []):
            for field in oneof.get('fields', []):
                all_type_names.append(field.get('type'))

    for rpc in service_spec.get('rpcs', []):
        all_type_names.extend(
            [rpc.get('command'), rpc.get('result'), rpc.get('event')])

    scalar_types = {'double', 'float', 'int32', 'int64', 'uint32', 'uint64', 'sint32',
                    'sint64', 'fixed32', 'fixed64', 'sfixed32', 'sfixed64', 'bool', 'string', 'bytes'}

    for type_name in filter(None, all_type_names):
        if not isinstance(type_name, str) or type_name.lower() in scalar_types:
            continue
        resolved_name = resolve_type_name(
            type_name, service_name, spec_data, package_prefix)
        resolved_type_names.append(resolved_name)

    if imports_to_add:
        content.append("")
        content.extend(sorted(list(imports_to_add)))
        content.append("")
    content.append(generate_enums_from_spec(service_spec.get('enums', [])))

    for msg_def in service_spec.get('messages', []):
        content.append(f"message {to_pascal_case(msg_def['name'])} {{")
        reserved_stmt = generate_reserved_statement(
            msg_def.get('reserved', []))
        if reserved_stmt:
            content.append(reserved_stmt)
        for oneof_def in msg_def.get('oneofs', []):
            content.append(f"  oneof {oneof_def['name']} {{")
            for field in oneof_def.get('fields', []):
                field['type'] = resolve_type_name(
                    field['type'], service_name, spec_data, package_prefix)
                content.append(f"  {format_field(field)}")
                resolved_type_names.append(field['type'])
            content.append("  }")
        for field in msg_def.get('fields', []):
            field['type'] = resolve_type_name(
                field['type'], service_name, spec_data, package_prefix)
            content.append(format_field(field))
            resolved_type_names.append(field['type'])
        content.append("}\n")

    command_rpcs, result_rpcs, event_rpcs = [], [], []
    for rpc in service_spec.get('rpcs', []):
        rpc_type = rpc.get('type', '').upper()
        rpc_id, rpc_name = rpc['id'], rpc['name']
        if rpc_type in ['REQUEST_ONLY', 'REQUEST_RESPONSE']:
            command_type = resolve_type_name(
                rpc['command'], service_name, spec_data, package_prefix)
            command_rpcs.append(f"    {command_type} {rpc_name} = {rpc_id};")
            resolved_type_names.append(command_type)
        if rpc_type == 'REQUEST_RESPONSE':
            result_type = resolve_type_name(
                rpc['result'], service_name, spec_data, package_prefix)
            result_rpcs.append(f"    {result_type} {rpc_name} = {rpc_id};")
            resolved_type_names.append(result_type)
        if rpc_type == 'NOTIFICATION':
            subscribe_command_name = f"subscribe_{rpc_name}"
            subscribe_type = resolve_type_name(
                f"{package_prefix}.windrpc.types.Subscribe", service_name, spec_data, package_prefix)
            resolved_type_names.append(subscribe_type)
            ack_type = resolve_type_name(
                f"{package_prefix}.windrpc.types.Empty", service_name, spec_data, package_prefix)
            resolved_type_names.append(ack_type)
            command_rpcs.append(
                f"    {subscribe_type} {subscribe_command_name} = {rpc_id};")
            result_rpcs.append(
                f"    {ack_type} {subscribe_command_name} = {rpc_id};")
            event_type = resolve_type_name(
                rpc['event'], service_name, spec_data, package_prefix)
            resolved_type_names.append(event_type)
            event_rpcs.append(f"    {event_type} {rpc_name} = {rpc_id};")


    import_paths = generate_import_paths(resolved_type_names)
    if len(import_paths) > 0:
        content.insert(3, "\n".join(import_paths))

    return "\n".join(content)


def _format_rpc_doc_comment(svc_name, svc_id, rpc):
    rpc_type = rpc.get('type', '').upper()
    rpc_name = rpc['name']
    rpc_id = rpc['id']
    desc = rpc.get('description', rpc.get('summary', 'No description provided.'))
    combined_id = combine_ids(svc_id, rpc_id)

    lines = []
    lines.append("  /**")
    lines.append(f"   * @service {svc_name}")
    lines.append(f"   * @rpc {rpc_name}")
    lines.append(f"   * @type {rpc_type}")
    lines.append(f"   * @id 0x{combined_id:04X} ({combined_id})")
    lines.append(f"   * @summary {desc}")

    if rpc_type in ['REQUEST_ONLY', 'REQUEST_RESPONSE']:
        lines.append(f"   * @param command {rpc.get('command', 'types.Empty')}")
    if rpc_type == 'REQUEST_RESPONSE':
        lines.append(f"   * @return result {rpc.get('result', 'types.Empty')}")
    elif rpc_type == 'REQUEST_ONLY':
        lines.append("   * @return void")
    elif rpc_type == 'NOTIFICATION':
        lines.append(f"   * @param subscribe types.Subscribe (enable=true/false)")
        lines.append(f"   * @event notification {rpc.get('event', 'types.Empty')}")

    lines.append("   */")
    return "\n".join(lines)


def generate_windrpc_proto(spec_data, package_prefix):

    content = [get_generated_file_header(), 'syntax = "proto3";\n',
               f'package {package_prefix}.windrpc.core;\n']
    for svc in spec_data['services']:
        content.append(
            f'import "{package_prefix}/windrpc/service/{svc["name"]}.proto";')
    content.append(f'import "{package_prefix}/windrpc/types/types.proto";\n')
    content.append(f"enum RpcId {{\n  RPC_ID_UNKNOWN = 0;\n")
    for svc in spec_data.get('services', []):
        svc_name = svc['name']
        svc_id = svc['id']
        for rpc in svc.get('rpcs', []):
            rpc_type = rpc.get('type', '').upper()
            doc_comment = _format_rpc_doc_comment(svc_name, svc_id, rpc)
            content.append(doc_comment)
            if rpc_type == 'NOTIFICATION':
                sub_name = f"subscribe_{rpc['name']}"
                content.append(
                    f"  RPC_ID_{svc_name.upper()}_{sub_name.upper()} = {combine_ids(svc_id, rpc['id'])};\n")
                event_combined_id = (svc_id << 8) | (rpc['id'] | 0x80)
                content.append(
                    f"  RPC_ID_{svc_name.upper()}_{rpc['name'].upper()} = {event_combined_id};\n")
            else:
                content.append(
                    f"  RPC_ID_{svc_name.upper()}_{rpc['name'].upper()} = {combine_ids(svc_id, rpc['id'])};\n")
    content.append('}\n')

    return "\n".join(content)


def generate(core_spec_path, user_spec_path, output_dir, verbose=False, strict=False):
    try:
        with open(core_spec_path, 'r', encoding='utf-8') as f:
            core_spec_data = yaml.load(f, Loader=LineNumberLoader)
        with open(user_spec_path, 'r', encoding='utf-8') as f:
            user_spec_data = yaml.load(f, Loader=LineNumberLoader)
    except FileNotFoundError as e:
        print(f"Error: Spec file not found - {e}", file=sys.stderr)
        sys.exit(1)
    except yaml.YAMLError as e:
        print(f"Error parsing YAML file: {e}", file=sys.stderr)
        sys.exit(1)

    spec_data = merge_specs(core_spec_data, user_spec_data)

    spec_validator.validate(spec_data, verbose=verbose, strict=strict)
    print("YAML Specification validation successful.")

    package_name = spec_data.get('package', 'default_package')
    output_path = os.path.join(output_dir, f"{package_name}/windrpc")
    os.makedirs(output_path, exist_ok=True)

    get_all_types(spec_data)

    print("\nGenerating .proto files...")

    # types.proto
    types_path = os.path.join(output_path, "types")
    os.makedirs(types_path, exist_ok=True)
    with open(os.path.join(types_path, "types.proto"), 'w', encoding='utf-8') as f:
        f.write(generate_types_proto(spec_data, package_name))
    print(f"Generated {os.path.join(types_path, 'types.proto')}")

    # windrpc/service/*.proto
    service_path = os.path.join(output_path, "service")
    os.makedirs(service_path, exist_ok=True)
    for service_spec in spec_data.get('services', []):
        file_path = os.path.join(service_path, f"{service_spec['name']}.proto")
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(generate_service_proto(
                service_spec, spec_data, package_name))
        print(f"Generated {file_path}")

    # windrpc/core/windrpc.proto
    core_path = os.path.join(output_path, "core")
    os.makedirs(core_path, exist_ok=True)
    with open(os.path.join(core_path, "windrpc.proto"), 'w', encoding='utf-8') as f:
        f.write(generate_windrpc_proto(spec_data, package_name))
    print(f"Generated {os.path.join(core_path, 'windrpc.proto')}")

    print("\nGenerating Nanopb options files...")
    options_generator.generate_options_files(
        spec_data, output_path, package_name, verbose=verbose)
    print("Nanopb options file generation complete.")

    print("\nProto file generation complete.")
